RushAKPsi/urls.py
from django.conf.urls import patterns, include, url
from RushAKPsi import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'RushAKPsi.views.home', name='home'),
    # url(r'^blog/', include('blog.urls')),

    url(r'^admin/', include(admin.site.urls)),

    url(r'', include('portal.urls')),
)  + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += patterns('',
    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT}),
)

portal/urls.py
from django.conf.urls import patterns, include, url
from portal.views import *
from RushAKPsi import settings
from django.conf.urls.static import static

urlpatterns = patterns('',

    url(r'^$', index_view),

    url(r'application/', application_view),

    url(r'login/', login_view),

    url(r'signup/', signup_view),

    url(r'gallery/', gallery_view),

    url(r'logout/', logout_view), 

    url(r'closed/', closed_view),

    url(r'rushee/(?P<rushee_id>\d+)/', rushee_view),
) + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

portal/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.contrib.auth.models import User
from portal.models import *
import re
from django.core.exceptions import ValidationError

class ExtFileField(forms.FileField):
    """
    Same as forms.FileField, but you can specify a file extension whitelist.

    >>> from django.core.files.uploadedfile import SimpleUploadedFile
    >>>
    >>> t = ExtFileField(ext_whitelist=(".pdf", ".txt"))
    >>>
    >>> t.clean(SimpleUploadedFile('filename.pdf', 'Some File Content'))
    >>> t.clean(SimpleUploadedFile('filename.txt', 'Some File Content'))
    >>>
    >>> t.clean(SimpleUploadedFile('filename.exe', 'Some File Content'))
    Traceback (most recent call last):
    ...
    ValidationError: [u'Not allowed filetype!']
    """
    def __init__(self, *args, **kwargs):
        ext_whitelist = kwargs.pop("ext_whitelist")
        self.ext_whitelist = [i.lower() for i in ext_whitelist]

        super(ExtFileField, self).__init__(*args, **kwargs)

    def clean(self, *args, **kwargs):
        data = super(ExtFileField, self).clean(*args, **kwargs)
        filename = data.name
        ext = os.path.splitext(filename)[1]
        ext = ext.lower()
        if ext not in self.ext_whitelist:
            raise forms.ValidationError("Resume must be a PDF file")

def is_andrew_email(value):
	a = re.compile("^[a-zA-Z0-9._%+-]+@andrew.cmu.edu$")
	a2 = re.compile("^[a-zA-Z0-9._%+-]+@cmu.edu$")
	if not (a.match(value) or a2.match(value)):
		raise ValidationError("Your email must be an Andrew email.")

def is_valid_phone_num(value):
	a = re.compile("^[0-9]")
	if len(value) != 10 or not a.match(value):
		raise ValidationError("Your phone number must be 10 digits long.")

def is_valid_grad_class(value):
	a = re.compile("^[0-9]")
	if len(value) != 4 or not a.match(value):
		raise ValidationError("Your graduating class must be 4 digits long.")

def is_valid_question(value):
	if len(value) > 1500:
		raise ValidationError("Please limit your responses to 250 words or less. ")

class NewUserForm(UserCreationForm):
	username = forms.CharField(label="Email", widget=forms.TextInput(attrs={'placeholder': 'Email', 'class': 'signup-field'}), 
								validators=[is_andrew_email])

	password1 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'signup-field'}))
	password2 = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Confirm Password', 'class': 'signup-field'}), label="Confirm Password")


	class Meta:
 		model = User
		fields = ("username", )

class NewRusheeForm(forms.Form):
	# keep these in the tope of the code
	q1 = forms.CharField(required=False, widget=forms.Textarea, label="Why do you want to be a member of Alpha Kappa Psi?", validators=[is_valid_question])
	q2 = forms.CharField(required=False, widget=forms.Textarea, label="Describe something meaningful you took away from a recruitment event or an interaction with a brother that makes you want to be a part of Alpha Kappa Psi.", validators=[is_valid_question])
	q3 = forms.CharField(required=False, widget=forms.Textarea, label="What is your business interest and what have you done so far to further that interest?", validators=[is_valid_question])
	q4 = forms.CharField(required=False, widget=forms.Textarea, label="(Optional) If there is additional information that you would like to share with us, please include it here- interesting facts, miscellaneous thoughts, experiences, or talents are welcome.", validators=[is_valid_question])
	picture = forms.ImageField(required=True, widget=forms.FileInput(attrs={'id': 'imgInp'}))
	first_name = forms.CharField(required=True, label="First Name", widget=forms.TextInput(attrs={'placeholder': 'First Name', 'class': 'question-primary'}))
	last_name = forms.CharField(required=True, label="Last Name", widget=forms.TextInput(attrs={'placeholder': 'Last Name', 'class': 'question-primary'}))
	phone_num = forms.CharField(required=True, label="Phone", widget=forms.TextInput(attrs={'placeholder': 'Phone Number', 'class': 'question-primary'}), validators=[is_valid_phone_num])
	grad_class = forms.CharField(required=True, label="Graduation Year", widget=forms.TextInput(attrs={'placeholder': 'Graduation Year', 'class': 'question-primary'}), validators=[is_valid_grad_class])
	major = forms.CharField(required=True, widget=forms.TextInput(attrs={'placeholder': 'Major', 'class': 'question-primary'}))
	gpa = forms.CharField(required=True, label="Cumulative GPA", widget=forms.TextInput(attrs={'placeholder': 'GPA', 'class': 'question-primary'}))	
	resume = ExtFileField(required=True, widget=forms.FileInput, ext_whitelist=[".pdf", ])

class LoginForm(forms.Form):
    username = forms.CharField(label="Email", widget=forms.TextInput(attrs={'placeholder': 'Email', 'class': 'signup-field'}))
    password = forms.CharField(widget=forms.PasswordInput(attrs={'placeholder': 'Password', 'class': 'signup-field'}))

templates/application.html
{% extends "base.html" %}

{% block title %}Rushee Application{% endblock %}

{% block content %}



<div class="app">
	
	{% include "sidebar.html" %}
		<div class="col-md-6 col-md-offset-1">
			<div class="app-form">
				{% if form.errors %}
					<div class="app-dialogue-error">
						<div class="app-dialogue-title">
							Plase Correct the Following
						</div>
						<div class="app-dialogue-body">
							<div class="singup-errors">
								{{form.errors}}
							</div>
						</div>
					</div>
				{% endif %}
				{% if splash %}
					<div class="app-dialogue">
						<div class="app-dialogue-title">
							Save Successful
						</div>
						<div class="app-dialogue-body">
							You've successfully saved your application. You can make changes up until the deadline (Sunday, September 14th @ 6pm), at which point your answers will be automatically submitted. Thank you for your interest in Alpha Kappa Psi at Carnegie Mellon.
						</div>
					</div>
				{% endif %}
				<div class="app-body">
				    <h2 class="text-center">Alpha Kappa Psi Application</h2>
				    <form class="form-horizontal" action="/application/" method="post" enctype="multipart/form-data">
				        {% csrf_token %}
				        <div class="row">
							<div class="col-md-4 col-md-offset-2">
								{% if rushee.picture %}
									<img id="pic" src="/media/{{ rushee.picture }}" width="210"/>{{ form.picture }}
								{% else %}
									<img id="pic" src="/static/images/Face.png" width="210"/>{{ form.picture }}
								{% endif %}
								<script type="text/javascript">
									function readURL(input) {

									    if (input.files && input.files[0]) {
									        var reader = new FileReader();

									        reader.onload = function (e) {
									            $('#pic').attr('src', e.target.result);
									        }

									        reader.readAsDataURL(input.files[0]);
									    }
									}

									$("#imgInp").change(function(){
									    readURL(this);
									});
								</script>
							</div>
			        		<div class="col-md-4">
			        			<span class="question-primary"> {{ form.first_name }} </span>
			        			<span class="question-primary"> {{ form.last_name }} </span>
			        			<span class="question-primary"> {{ form.phone_num }} </span>
			        			<span class="question-primary"> {{ form.grad_class}} </span>
			        			<span class="question-primary"> {{ form.major}} </span>
			        			<span class="question-primary"> {{ form.gpa }} </span>
			        		</div>
		        		</div>
		        		<div class="row">
		        			<div class="col-md-8 col-md-offset-2">
			        			<div class="questions-long">
				        			{% for field in form %}
				        				<div class="question-long">
											{% if "id_q" in field.id_for_label %}
												<!-- <span class="question-title"><strong> Question {{ forloop.counter }} </strong></span>
												<br> -->
												{{ field.label_tag }}
												{{ field }}
												<p id="counter{{ forloop.counter }}"></p>
											{% endif %}
				        				</div>
				        			{% endfor %}
				        			<script>
				        			var maxLen = 1500;
				        			var q1 = $("#id_q1");
				        			var q2 = $("#id_q2");
				        			var q3 = $("#id_q3");
				        			var q4 = $("#id_q4");
				        			var c1 = $("#counter1");
				        			var c2 = $("#counter2");
				        			var c3 = $("#counter3");
				        			var c4 = $("#counter4");

				        			function updateCounter(question, counter) {
				        				console.log("HI");
				        				var remLength = 0;
				        				remLength = maxLen - parseInt(question.val().length);
				        				if (remLength < 0) {
				        					question.val() = question.val().substring(0, maxLen);
				        					return false;
				        				}
				        				counter.text(remLength + " characters remaining");
				        			}
				        			$(document).ready(function() {
				        			q1.keypress(updateCounter(q1, c1));
				        			q2.keypress(updateCounter(q2, c2));
				        			q3.keypress(updateCounter(q3, c3));
				        			q4.keypress(updateCounter(q4, c4));
				        			});	
				        			</script>
				        		</div>
				        	</div>
		        		</div>
		        		<div class="row">
		        			<div class="resume">
			        			<div class="col-md-2 col-md-offset-2">
			        				<span class="resume-label">{{ form.resume.label_tag }}</span>
			        			</div>
			        			<div class="col-md-3">
			        				<div class="fileupload">
			        				  {{ form.resume }}
			        				  + Add New File
			        				</div>
			        			</div>
			        			<div class="col-md-3">
			        				<div class="resume-name">
			        					{{rushee.resume}}

				        			</div>
				        			<script>

				        				$( "input[name='resume']" ).change(function() {
				        					pathName = $("input[name='resume']").val();
				        					fileName = pathName.match(/[^\/\\]+$/);
				        				  	$(".resume-name").text(fileName);
				        				});
				        				if ($(".resume-name").text()){
				        					trimmed = $.trim($(".resume-name").text());
				        					sliced = trimmed.slice(12);
				        					$(".resume-name").text(sliced);
				        				}

				        			</script>
			        			</div>
			        		</div>
		        		</div>
		        	</div>
	        		<div class="row">
	        			<div class="col-md-4 col-md-offset-4">
	        				<div class="save-area">
	        					<button id="save" type="submit" value="save" class="signup-btn btn-block">Save</button>
	        					<script type="text/javascript">
	        						// $("#save").click(function() {
	        						// 	alert("fdjskln");
	        						// 	$(".app-dialogue").hide();
	        						// })
	        					</script>
	        				</div>
	        			</div>
	        		</div>
		        		
			    </form>
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/base.html
<!DOCTYPE html>
<html>

<head>
	<link rel="shortcut icon" href="/static/logo.png">
	<meta http-equiv="Content-Type" content="text/html;charset=utf-8" />
	<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
	<link href='http://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600' rel='stylesheet' type='text/css'>
	<link href="/static/css/bootstrap.css" rel="stylesheet" />
	<script src="/static/js/bootstrap.js"></script>
	<link href="/static/css/custom.css" rel="stylesheet" />
	<title>{% block title %}{% endblock %}</title>
</head>

<body>
	<div class="container-fluid">
		{% block content %}
		{% endblock %}
	</div>
</body>

</html>

templates/closed.html
{% extends "base.html" %}

{% block title %}Rushee Application{% endblock %}

{% block content %}



<div class="app">
{% include "sidebar.html" %}
	<div class="col-md-6">
		<div class="app-form">
			<div class="app-body">
			    <h2 class="text-center">Alpha Kappa Psi Application</h2>
			    <div class="row">
	        		<div class="col-md-10 col-md-offset-1">
			    		<p>Thank you for applying for membership to Alpha Kappa Psi. The application portal is now closed for this semester. If you are interested in upcoming recruitments periods, please contact <a href="mailto:nlam@andrew.cmu.edu" target="_top">Nicholas Lam.</a></p>
			    	</div>
			    </div>
			</div>
		</div>
	</div>
</div>

{% endblock %}

templates/gallery.html
{% extends "base.html" %}

{% block title %}Rushees{% endblock %}

{% block content %}
{% include "sidebar.html" %}
<div class="col-md-6 col-md-offset-1">
	<div class="app-form">
		<div class="app-body">
			<h2 class="text-center"> Rushees ({{rushees.count}}) </h2>
			<table class="table table-striped">
				<thead>
					<tr>
						<th>Complete?</th>
						<th>Name</th>
						<th>Year</th>
						<th>Major</th>
						<th>Email</th>
					</tr>
				</thead>
				<tbody>
					{% for rushee in rushees %}
						<tr>
							<td>{% if rushee.complete == true %}Yes!{% else %}No :({% endif %}</td>
							<td><a href="/rushee/{{ rushee.id }}">{{ rushee.first_name }} {{ rushee.last_name }}</a></td>
							<td>{{ rushee.grad_class}}</td>
							<td>{{ rushee.major}}</td>
							<td>{{ rushee.user.username}}</td>
						</tr>
					{% endfor %}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block title %}Alpha Kappa Psi Fall Rush{% endblock %}

{% block content %}

<div class="row">
	{% include "sidebar.html" %}
	<div class="col-md-3 col-md-offset-2">
		<div class="signup">
			<h1 class="signup-title">
				Rush
			</h1>
			<h3 class="signup-subtitle">
				Alpha Kappa Psi
			</h3>
			<div class="signup-area">
				<a href="/login"><div class="signup-btn">Log In</div></a>
				<a><div class="title"><span>Or</span></div></a>
				<a href="/signup"><div class="signup-btn">Sign Up</div></a>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}Log in{% endblock %}

{% block content %}
<div class="row">
	{% include "sidebar.html" %}
	<div class="col-md-3 col-md-offset-2">
		<div class="signup">
			<span class="signup-title">
				Rush
			</span>
			<span class="signup-subtitle">
				Alpha Kappa Psi
			</span>
			<div class="signup-area">
				{% if error %}
					<div class="signup-errors">
						{{ error }}
					</div>
				{% endif %}
				<div class="signup_form">
				    <form action="" method="post">
				        {% csrf_token %}
				        {% for field in form %}
				        	{{field}}
				        {% endfor %}
				        <button type="submit" value="Submit" class="entry-btn btn-block">Log In</button>
				    </form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

templates/rushee.html
{% extends "base.html" %}
{% block title %}{{ rushee.first_name }} {{ rushee.last_name }}{% endblock %}

{% block content %}
{% include "sidebar.html" %}
<div class="col-md-6 col-md-offset-1">
	<div class="app-form">
		<div class="app-body">
		<h2 class="text-center">{{ rushee.first_name }} {{rushee.last_name}}</h2>
	        <div class="row">
				<div class="col-md-4 col-md-offset-2">
					{% if rushee.picture %}
						<img id="pic" src="/media/{{ rushee.picture }}" width="210"/>
					{% else %}
						<img id="pic" src="/static/images/Face.png" width="210"/>
					{% endif %}
				</div>
        		<div class="col-md-4">
        			<strong>Email:</strong>
        			<div class="question-primary">{{ rushee.user.username }}</div>
        			<strong>Name:</strong>
        			<div class="question-primary"> {{ rushee.first_name }} {{ rushee.last_name }} </div>
        			<strong>Phone Number:</strong>
        			<div class="question-primary"> {{ rushee.phone_num }} </div>
        			<strong>Year:</strong>
        			<div class="question-primary"> {{ rushee.grad_class}} </div>
        			<strong>Major:</strong>
        			<div class="question-primary"> {{ rushee.major}} </div>
        			<strong>GPA:</strong>
        			<div class="question-primary"> {{ rushee.gpa }} </div>
        		</div>
    		</div>
    		<div class="row">
    			<div class="col-md-8 col-md-offset-2">
    				<p class="gallery-question" class="gallery-question">Describe your business interests.</p>
    				<p>{{ rushee.q1 }}</p>
    				<p class="gallery-question">Describe something meaningful you took away from a recruitment event or an interaction with a brother that makes you want to be a part of Alpha Kappa Psi.</p>
    				<p>{{ rushee.q2 }}</p>
    				<p class="gallery-question">What specifically do you hope to gain from membership in Alpha Kappa Psi?</p>
    				<p>{{ rushee.q3 }}</p>
    				<p class="gallery-question">(Optional) If there is additional information that you would like to share with us, please include it here- interesting facts, miscellaneous thoughts, experiences, or talents are welcome."</p>
    				<p>{{ rushee.q4 }}</p>
    				<embed src="/media/{{ rushee.resume }}" width="440px." height="500px">
	        	</div>
    		</div>
    		
		</div>
	</div>
</div>
{% endblock %}

templates/sidebar.html
<div class="col-md-3">
		<div class="sidebar">
			<a href="/"><img src="/static/images/logo.png" width="150"></a>
			{% if user.is_authenticated %}
				<a href="/logout"><div class="login-btn">Logout</div></a>
			{% endif %}
			<div class="sidebar-info">
				<span class="sidebar-info-title">Application Deadline</span>
				<span class="sidebar-info-text">{{ DUE_DATE | safe }}</span>
				<br><br>
				<span class="sidebar-info-title">Questions?</span>
				<span class="sidebar-info-text">Contact your AKPsi Rep or <a href="mailto:nlam@andrew.cmu.edu" target="_top">Nicholas Lam.</a></span>
			</div>
			<div class="sidebar-sponsor">
				<img src="/static/images/BNY_logo.png" width="150">
			</div>
		</div>
	</div>

templates/signup.html
{% extends "base.html" %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="row">
	{% include "sidebar.html" %}
	<div class="col-md-3 col-md-offset-2">
		<div class="signup">
			<h1 class="signup-title">
				Rush
			</h1>
			<h3 class="signup-subtitle">
				Alpha Kappa Psi
			</h3>
			<div class="signup-area">
				{% if form.errors %}
					<div class="signup-errors">
						{{ form.errors }}
					</div>
				{% endif %}
				<div class="signup_form">
				    <form action="" method="post">

				        {% csrf_token %}
				        {% for field in form %}
				        	{{field}}
				        {% endfor %}

				        <button type="submit" value="Submit" class="entry-btn btn-block">Sign Up</button>
				    </form>
				</div>
					<script type="text/javascript">
					$( ".signup-btn btn-block" ).click(function() {
						// $( ".signup-errors" ).change(function() {
						//   alert( "Handler for .change() called." );
						// });
						alert( "Handler for .change() called." );
					});
					</script>
			</div>
		</div>
	</div>
</div>


{% endblock %}